name: coffee_timer
description: Brew delicious coffee with Timer.Coffee
publish_to: 'none'
version: 1.0.9+10

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_linkify: ^5.0.2
  intl: ^0.17.0
  url_launcher: ^6.0.12
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  ionicons: ^0.2.2
  wakelock: ^0.6.2
  in_app_review: ^2.0.6
  package_info_plus: ^3.0.0
  flutter_markdown: ^0.6.15
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
   - family:  CoffeeTimerIcons
     fonts:
     - asset: fonts/CoffeeTimerIcons.ttf
   - family:  Lato
     fonts:
     - asset: fonts/Lato-Regular.ttf
     - asset: fonts/Lato-Bold.ttf
       weight: 700

  assets:
    - assets/data/brewing_methods.json
    - assets/data/recipes_v60.json
    - assets/data/recipes_aeropress.json
    - assets/data/recipes_chemex.json
    - assets/data/recipes_frenchpress.json
    - assets/data/recipes_clever.json
    - assets/data/recipes_kalita.json
    - assets/data/recipes_wilfa.json
    - assets/data/coffee_facts.json
    - assets/CONTRIBUTORS.md
